services:
  - type: web
    name: rembg-api
    runtime: python

    buildCommand: |
      apt-get update && apt-get install -y libgl1
      pip install -r requirements.txt

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120

    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"

    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "*"